# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor']

# Site settings
title: Sarath Sasindrakumar
email: sarathvss65@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  I’m Sarath Sasindrakumar, and I’m a full stack software engineer based in Chennai, India.
  I primarily enjoy working with Java and JavaScript but I’m always seeking ways to expand my
  knowledge and learn about new tools, languages and frameworks. In addition to software development,
  my other loves include reading, writing, music, cycling, hiking, travelling!
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.blog.sarathsasindrakumar.com" # the base hostname & protocol for your site
twitter_username: SarathVS65
github_username:  netooran

# Build settings
markdown: kramdown
permalink: /:title

gems:
  - jekyll-seo-tag
  - jekyll-paginate
twitter:
  username: SarathVS65
author: sarathvs
layout: default
comments: true
excerpt_separator: <!--more-->
paginate: 10
future: true
